name: Build Node.js User API

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # Define environment variables here
      DOCKER_IMAGE: user-api

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    # Step 3: Navigate to the API directory and install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run Tests
      run: npm test -- --forceExit

    # Step 5: Set up Docker Buildx (needed for multi-platform builds, optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 6: Build Docker image
    - name: Build Docker Image
      working-directory: ./API
      run: |
        docker build -t $DOCKER_IMAGE:$GITHUB_SHA .
