version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    container_name: db 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - nodejs-mysql
  app:
    image: node:20.11.0-alpine
    user: ${NODE_USER}
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
    command: "yarn start"
    deploy:
      replicas: 3
    volumes:
      - ./:/home/node/app
    depends_on:
      - mysql
    networks:
      - nodejs-mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nodejs-mysql
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080" 
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - nodejs-mysql
volumes:
  mysql:
  jenkins_home:
networks:
  nodejs-mysql:
    driver: bridge
